version: '3.8'

services:
  xml-translator:
    build: .
    ports:
      - "3000:3000"
    environment:
      - FLASK_ENV=production
    volumes:
      - ./uploads:/tmp/uploads
      - ./outputs:/tmp/outputs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

volumes:
  uploads:
  outputs:
